CREATE DATABASE QI;

CREATE TABLE Tasks
(
   Id INT AUTO_INCREMENT PRIMARY KEY,
   Title VARCHAR(255) NOT NULL,
   Descriotion TEXT,
   ReminderDate DATETIME NULL,
   Completed BOOLEAN DEFAULT FALSE
);

SELECT* FROM Tasks